# Generated by Django 5.2 on 2025-04-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
